// export const locations = [
//   "Anjar",
//   "Bawal",
//   "Baytown",
//   "BMM",
//   "BPSL",
//   "Dhar",
//   "Dolvi",
//   "Head Office",
//   "Kalmeshwar",
//   "Khopoli",
//   "Raigarh",
//   "Rajpura",
//   "Salav",
//   "Salem",
//   "Tarapur",
//   "Vasind",
//   "Vijayanagar",
// ];

// export const clusters = [
//   "Blast Furnace",
//   "Coated",
//   "Coke Oven",
//   "Electrical & Automation",
//   "Energy",
//   "ESG",
//   "Logistics",
//   "Maintenance",
//   "MILLS",
//   "PDQC",
//   "Pellet",
//   "Plates",
//   "Refractory",
//   "RMHS",
//   "Safety",
//   "Sinter",
//   "SIP",
//   "SMS",
//   "Utility & Power",
// ];


export const locations = [
  "Anjar",
  "Bawal",
  "Baytown",
  "BMM",
  "BPSL",
  "Dhar",
  "Dolvi",
  "Head Office",
  "Kalmeshwar",
  "Khopoli",
  "Raigarh",
  "Rajpura",
  "Salav",
  "Salem",
  "Tarapur",
  "Vasind",
  "Vijayanagar",
]

.map((name, i) => ({
  name,
  color: `hsl(${(i * 25) % 360}, 70%, 55%)`,
}));

export const clusters = [
  "Blast Furnace",
  "Coated",
  "Coke Oven",
  "Electrical & Automation",
  "Energy",
  "ESG",
  "Logistics",
  "Maintenance",
  "MILLS",
  "PDQC",
  "Pellet",
  "Plates",
  "Refractory",
  "RMHS",
  "Safety",
  "Sinter",
  "SIP",
  "SMS",
  "Utility & Power",
]

.map((name, i) => ({
  name,
  color: `hsl(${(i * 40) % 360}, 70%, 60%)`,
}));



export const clusterLocations = [
  { cluster: "Refractory", location: "Dolvi" },
  { cluster: "Refractory", location: "Vijayanagar" },
  { cluster: "Refractory", location: "BPSL" },
  { cluster: "Refractory", location: "Raigarh" },
  { cluster: "Refractory", location: "Salem" },
  { cluster: "Refractory", location: "BMM" },

  { cluster: "SMS", location: "Vijayanagar" },
  { cluster: "SMS", location: "Dolvi" },
  { cluster: "SMS", location: "BPSL" },
  { cluster: "SMS", location: "Raigarh" },
  { cluster: "SMS", location: "Salem" },
  { cluster: "SMS", location: "Mingo Jn" },
  { cluster: "SMS", location: "BMM" },

  { cluster: "ESG", location: "Vijayanagar" },
  { cluster: "ESG", location: "Dolvi" },
  { cluster: "ESG", location: "BPSL" },
  { cluster: "ESG", location: "Raigarh" },
  { cluster: "ESG", location: "Salem" },
  { cluster: "ESG", location: "Anjar" },
  { cluster: "ESG", location: "BMM" },
  { cluster: "ESG", location: "Salav" },

  { cluster: "Electrical & Automation", location: "Anjar" },
  { cluster: "Electrical & Automation", location: "BPSL" },
  { cluster: "Electrical & Automation", location: "Dolvi" },
  { cluster: "Electrical & Automation", location: "Raigarh" },
  { cluster: "Electrical & Automation", location: "Salav" },
  { cluster: "Electrical & Automation", location: "Salem" },
  { cluster: "Electrical & Automation", location: "Vijayanagar" },

  { cluster: "Logistics", location: "Anjar" },
  { cluster: "Logistics", location: "BMM" },
  { cluster: "Logistics", location: "BPSL" },
  { cluster: "Logistics", location: "Dolvi" },
  { cluster: "Logistics", location: "Raigarh" },
  { cluster: "Logistics", location: "Rajpura" },
  { cluster: "Logistics", location: "Salav" },
  { cluster: "Logistics", location: "Salem" },
  { cluster: "Logistics", location: "Vijayanagar" },
  { cluster: "Logistics", location: "Vasind" },
  { cluster: "Logistics", location: "Tarapur" },
  { cluster: "Logistics", location: "Kalmeshwar" },
  { cluster: "Logistics", location: "Khopoli" },
  { cluster: "Logistics", location: "Bawal" },
  { cluster: "Logistics", location: "Dhar" },

  { cluster: "Safety", location: "Anjar" },
  { cluster: "Safety", location: "Bawal" },
  { cluster: "Safety", location: "BMM" },
  { cluster: "Safety", location: "BPSL" },
  { cluster: "Safety", location: "Dolvi" },
  { cluster: "Safety", location: "Kalmeshwar" },
  { cluster: "Safety", location: "Khopoli" },
  { cluster: "Safety", location: "Raigarh" },
  { cluster: "Safety", location: "Rajpura" },
  { cluster: "Safety", location: "Salav" },
  { cluster: "Safety", location: "Salem" },
  { cluster: "Safety", location: "Tarapur" },
  { cluster: "Safety", location: "Vasind" },
  { cluster: "Safety", location: "Vijayanagar" },
  { cluster: "Safety", location: "Dhar" },

  { cluster: "Blast Furnace", location: "BPSL" },
  { cluster: "Blast Furnace", location: "Dolvi" },
  { cluster: "Blast Furnace", location: "Raigarh" },
  { cluster: "Blast Furnace", location: "Salem" },
  { cluster: "Blast Furnace", location: "Vijayanagar" },
  { cluster: "Blast Furnace", location: "BMM" },

  { cluster: "Coke Oven", location: "BPSL" },
  { cluster: "Coke Oven", location: "Dolvi" },
  { cluster: "Coke Oven", location: "Salem" },
  { cluster: "Coke Oven", location: "Vijayanagar" },

  { cluster: "MILLS", location: "BPSL" },
  { cluster: "MILLS", location: "Dolvi" },
  { cluster: "MILLS", location: "Salem" },
  { cluster: "MILLS", location: "Vijayanagar" },

  { cluster: "PDQC", location: "Anjar" },
  { cluster: "PDQC", location: "Bawal" },
  { cluster: "PDQC", location: "BPSL" },
  { cluster: "PDQC", location: "Dhar" },
  { cluster: "PDQC", location: "Dolvi" },
  { cluster: "PDQC", location: "Kalmeshwar" },
  { cluster: "PDQC", location: "Khopoli" },
  { cluster: "PDQC", location: "Raigarh" },
  { cluster: "PDQC", location: "Rajpura" },
  { cluster: "PDQC", location: "Salem" },
  { cluster: "PDQC", location: "Tarapur" },
  { cluster: "PDQC", location: "Vasind" },
  { cluster: "PDQC", location: "Vijayanagar" },

  { cluster: "SIP", location: "BMM" },
  { cluster: "SIP", location: "BPSL" },
  { cluster: "SIP", location: "Dolvi" },
  { cluster: "SIP", location: "Raigarh" },
  { cluster: "SIP", location: "Salav" },
  { cluster: "SIP", location: "Vijayanagar" },

  { cluster: "Energy", location: "BMM" },
  { cluster: "Energy", location: "BPSL" },
  { cluster: "Energy", location: "Dolvi" },
  { cluster: "Energy", location: "Raigarh" },
  { cluster: "Energy", location: "Salem" },
  { cluster: "Energy", location: "Vijayanagar" },

  { cluster: "Pellet", location: "BMM" },
  { cluster: "Pellet", location: "BPSL" },
  { cluster: "Pellet", location: "Dolvi" },
  { cluster: "Pellet", location: "Raigarh" },
  { cluster: "Pellet", location: "Vijayanagar" },

  { cluster: "Sinter", location: "BPSL" },
  { cluster: "Sinter", location: "Dolvi" },
  { cluster: "Sinter", location: "Raigarh" },
  { cluster: "Sinter", location: "Salem" },
  { cluster: "Sinter", location: "Vijayanagar" },

  { cluster: "RMHS", location: "BMM" },
  { cluster: "RMHS", location: "BPSL" },
  { cluster: "RMHS", location: "Dolvi" },
  { cluster: "RMHS", location: "Raigarh" },
  { cluster: "RMHS", location: "Salav" },
  { cluster: "RMHS", location: "Salem" },
  { cluster: "RMHS", location: "Vijayanagar" },

  { cluster: "Utility & Power", location: "Anjar" },
  { cluster: "Utility & Power", location: "BMM" },
  { cluster: "Utility & Power", location: "BPSL" },
  { cluster: "Utility & Power", location: "Dolvi" },
  { cluster: "Utility & Power", location: "Raigarh" },
  { cluster: "Utility & Power", location: "Salav" },
  { cluster: "Utility & Power", location: "Salem" },
  { cluster: "Utility & Power", location: "Vijayanagar" },

  { cluster: "Plates", location: "Anjar" },
  { cluster: "Plates", location: "Baytown" },

  { cluster: "Coated", location: "Bawal" },
  { cluster: "Coated", location: "BPSL" },
  { cluster: "Coated", location: "Dhar" },
  { cluster: "Coated", location: "Kalmeshwar" },
  { cluster: "Coated", location: "Khopoli" },
  { cluster: "Coated", location: "Rajpura" },
  { cluster: "Coated", location: "Tarapur" },
  { cluster: "Coated", location: "Vasind" },
  { cluster: "Coated", location: "Vijayanagar" },

  { cluster: "Maintenance", location: "Vijayanagar" },

  { cluster: "SEED", location: "BPSL" },
  { cluster: "SEED", location: "Dolvi" },
  { cluster: "SEED", location: "Salem" },
  { cluster: "SEED", location: "Vijayanagar" },
];

